/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebas.adivinaquien;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import misClases.Personaje;
/**
 *
 * @author Edson Leonardo
 */
public class gameplay extends javax.swing.JFrame {

    /**
     * Creates new form gameplay
     */
    private JButton btn;
    
    
    private JPanel jPanel2;

    public gameplay() {
        setTitle("Adivina Quién");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setLayout(null); // Desactivamos layout automático

        // Crear jPanel2 y establecer su tamaño más pequeño que el JFrame
        jPanel2 = new JPanel();
        jPanel2.setLayout(new GridLayout(4, 6, 5, 5)); // 4 filas, 6 columnas
        jPanel2.setBackground(Color.DARK_GRAY);
        jPanel2.setBounds(50, 50, 700, 450); // x, y, ancho, alto

        add(jPanel2);

        List<Personaje> todos = new ArrayList<>();
        // Agrega aquí tus 32 personajes reales
        todos.add(new Personaje("Cartel", "imagenes/cartel.png"));
        todos.add(new Personaje("Afilador", "imagenes/afilador.png"));
        todos.add(new Personaje("Antorcha", "imagenes/antorcha.png"));
        todos.add(new Personaje("Ballesta", "imagenes/ballesta.png"));
        todos.add(new Personaje("Carne", "imagenes/carnepodrida.png"));
        todos.add(new Personaje("Caña", "imagenes/cañadepescar.png"));
        todos.add(new Personaje("EndCrystal", "imagenes/endcrystal.png"));
        todos.add(new Personaje("EnderChest", "imagenes/enderchest.png"));
        todos.add(new Personaje("EnderPerl", "imagenes/enderperl.png"));
        todos.add(new Personaje("Escudo", "imagenes/escudo.png"));
        todos.add(new Personaje("Espada", "imagenes/espadamadera.png"));
        todos.add(new Personaje("Glowston", "imagenes/glowston.png"));
        todos.add(new Personaje("Ice", "imagenes/iceblue.png"));
        todos.add(new Personaje("Lana Rosa", "imagenes/lanarosa.png"));
        todos.add(new Personaje("Leche", "imagenes/libroencantado.png"));
        todos.add(new Personaje("Leche", "imagenes/lingotedecobre.png"));
        todos.add(new Personaje("Leche", "imagenes/melon.png"));
        todos.add(new Personaje("Leche", "imagenes/obsidianallorosa.png"));
        todos.add(new Personaje("Leche", "imagenes/ojodearaña.png"));
        todos.add(new Personaje("Leche", "imagenes/pararayos.png"));
        todos.add(new Personaje("Leche", "imagenes/piconetherite.png"));
        todos.add(new Personaje("Leche", "imagenes/pluma.png"));
        todos.add(new Personaje("Leche", "imagenes/saplig.png"));
        todos.add(new Personaje("Leche", "imagenes/scaffolding.png"));
        todos.add(new Personaje("Leche", "imagenes/skeletonskull.png"));
        todos.add(new Personaje("Leche", "imagenes/tierra.png"));
        todos.add(new Personaje("Leche", "imagenes/totem.png"));
        todos.add(new Personaje("Leche", "imagenes/tridente.png"));
        todos.add(new Personaje("Leche", "imagenes/visionnocturna.png"));


        // Mezclar y tomar 24 personajes aleatorios
        Collections.shuffle(todos);
        List<Personaje> seleccionados = todos.subList(0, 24);

        for (Personaje p : seleccionados) {
            JButton boton = new JButton(p.getNombre(), p.getImagen());
            boton.setPreferredSize(new Dimension(100, 100));
            boton.setVerticalTextPosition(SwingConstants.BOTTOM);
            boton.setHorizontalTextPosition(SwingConstants.CENTER);
            jPanel2.add(boton);
        }

        setVisible(true);
    }


        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
